video3dom/utils/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path("signup/", views.go_404, name="account_signup"),
    path("login/", views.go_404, name="account_login"),
    path("logout/", views.go_404, name="account_logout"),
    path("reauthenticate/", views.go_404, name="account_reauthenticate"),
    path(
        "password/change/",
        views.go_404,
        name="account_change_password",
    ),
    path("password/set/", views.go_404, name="account_set_password"),
    path("inactive/", views.go_404, name="account_inactive"),
    # Email
    path("email/", views.go_404, name="account_email"),
    path(
        "confirm-email/",
        views.go_404,
        name="account_email_verification_sent",
    ),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        views.go_404,
        name="account_confirm_email",
    ),
    # password reset
    path("password/reset/", views.go_404, name="account_reset_password"),
    path(
        "password/reset/done/",
        views.go_404,
        name="account_reset_password_done",
    ),
    re_path(
        r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.go_404,
        name="account_reset_password_from_key",
    ),
    path(
        "password/reset/key/done/",
        views.go_404,
        name="account_reset_password_from_key_done",
    ),
]

video3dom/video3dom/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('video3domapp.urls', namespace='video3domapp')),
    path('accounts/', include('utils.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
    path('actions-DB/', include('actions_DB.urls')),
    path('import-video/', include('video3importvideoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

video3dom/video3domapp/urls.py
from django.urls import path
from .views import Home, Visionnage

app_name = "video3domapp"

urlpatterns = [
    path('', Home.as_view(), name="Home"),
    path('Visionnage/<uuid:uuid>', Visionnage.as_view(), name="Visionnage"),
]

video3dom/templates/single_video.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- ========== MAIN CONTENT ========== -->
<main id="content">
    <div class="container px-md-5">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'video3domapp:Home' %}">Accueil</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{movie}}</li>
            </ol>
        </nav>
        <div class="row mb-4">
            <div class="col-md-8 col-xl-9 mb-4">
                <div class="position-relative min-h-270rem mb-2d mr-xl-3">
                    {% if request.user.is_authenticated %}
                    {% if movie.creator.channel == 'youtube' %}
                        <iframe class="position-absolute w-100 h-lg-down-100 position-xl-relative top-0 bottom-0 w-100" height="620" src="https://www.youtube.com/embed/{{movie.channel_external_id}}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    {% elif movie.creator.channel == 'local' %}
                        <video
                                class="position-absolute w-100 h-lg-down-100 position-xl-relative top-0 bottom-0 w-100" height="620" controls><source src="{{movie.file.url}}" type="video/mp4"></video>
                    {% else %}
                        <iframe class="position-absolute w-100 h-lg-down-100 position-xl-relative top-0 bottom-0 w-100" height="620" src="{{movie.video_url}}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    {% endif %}
                    {% else %}
                        <div height="620">
                            <p>Veuillez vous identifier avant de visionner une vidéo.</p>
                        </div>
                    {% endif %}
                </div>
                <div class="mr-xl-3">
                    <div class="mb-2">
                        <h5 class="font-size-21 text-dark font-weight-medium">{{movie.title}}</h5>
                    </div>

                    <div class="font-size-12 mb-4">
                        <span class="d-inline-flex text-gray-1300 align-items-center mr-3">Publié le {% firstof movie.date_published movie.file_date %}</span>
                        <span class="d-inline-flex text-gray-1300 align-items-center mr-3">| par {{movie.creator.name}}</span>
                    </div>


                    <div class="collapse" id="collapseExample">
                        <div class="card card-body shadow-none p-0 mb-2">
                            <p>{% firstof movie.description movie.file_tags %}</p>
                        </div>
                    </div>

                    <div>
                        <a class="show-more-arrow font-size-14" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Show more <i class="ml-1d fas fa-chevron-down font-size-10"></i>
                        </a>
                    </div>


                </div>
            </div>

            <div class="col-md-4 col-xl-3">
                <a href="#" class="d-block mb-3d">
                    <img class="img-fluid" src="https://placehold.it/350x277" alt="Image-Description">
                </a>

                <div class="mb-4">
                    <h5 class="text-gray-700 font-size-18 font-weight-medium">Du meme créateur de contenu</h5>

                    {% for m in movies_3 %}
                    <div class="row d-block d-xl-flex align-items-center no-gutters mb-2d">
                        <div class="col product-image mb-2d mb-xl-0">
                            <a href="{% url 'video3domapp:Visionnage' m.uuid %}" class="d-block  stretched-link">
                                <img class="img-fluid" src="{{ m.image_url }}" alt="Image-Description">
                            </a>
                        </div>
                        <div class="col">
                            <div class="mx-xl-2d">
                                <div class="product_title font-size-13 font-weight-semi-bold mb-1d">
              <a href="{% url 'video3domapp:Visionnage' m.uuid %}" class="">{{ m.title|striptags }}</a>
                                </div>

                                <div class="product-meta dot font-size-12 mb-1">
                                    <span class="d-inline-flex text-gray-1300">{{ m.created_in_3dom }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>


    </div>
</main>
<!-- ========== END MAIN CONTENT ========== -->


{% endblock content %}